version: '3'

vars:
  PIO_ENV: xiao_c3

tasks:
  tools:
    desc: Install uv tools
    cmds:
      - 'uv tool install platformio --with pip --force'
      
  init:
    desc: Initialize the repo
    cmds:
      - '[ -f config/Config.h ] || cp config/Config.h.sample config/Config.h'
      - '[ -f config/Certificate.h ] || cp config/Certificate.h.sample config/Certificate.h'
      - 'git config core.hooksPath .githooks'


  default:
    cmds:
      - task -l
    silent: true
  # default:
  #   desc: Run the build task
  #   cmds:
  #     - task: build

  build:
    desc: Build the firmware
    cmds:
      - pio run -e {{.PIO_ENV}}

  upload:
    desc: Upload/flash the firmware to the device
    cmds:
      - pio run -t upload -e {{.PIO_ENV}}

  monitor:
    desc: Open the serial monitor
    cmds:
      - pio device monitor

  clean:
    desc: Clean build artifacts
    cmds:
      - pio run -t clean -e {{.PIO_ENV}}

  lint-yaml:
    desc: Lint YAML files
    cmds:
      - yamllint-rs .

  lint-markdown:
    desc: Lint Markdown files
    cmds:
      - rumdl check .
