name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  target:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Setup Python & uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'

      - name: PlatformIO Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO Core
        run: uv pip install --system platformio

      - name: Build with PlatformIO
        run: ./script/ci
